buildscript {
  ext.kotlin_version = '1.9.22'
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:8.2.2'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}

ext {
  //Rakam version
  RAKAM_VERSION = '2.7.14'
  FACEBOOK_SDK_VERSION = '7.0.0'
}
