apply plugin: 'java-library'
apply plugin: 'kotlin'

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  api project(path: ':aptoide-authentication-core')

  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.7.3")
  implementation("io.reactivex.rxjava2:rxjava:2.2.21")
}
